### ISSUE TITLE
Does this support cluster upgrades?

### ISSUE THREAD

**Issue by bellitech** [codedellemc/puppet-scaleio#10]
I don't see references to the support of upgrades to an entire infrastructure. Is that accurate?

**Comment by jonasrosland** [comment]
Hi @bellitech, correct, this isn't built for upgrading ScaleIO. We've talked to the core developers of ScaleIO and their recommended and supported mechanism is to use their supplied packaged tools for upgrades.

**Comment by Andrey-mp** [comment]
Closed due to new version in repository.
