### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by Boran** [codedellemc/puppet-scaleio#20]
Hi, the readme indicates Ubuntu 14.04, has any tests or work been done on 16.04 yet?

**Comment by Andrey-mp** [comment]
Hi. Yes, we've tested 16.04 with newton yesterday - and found it works well.

**Comment by Andrey-mp** [comment]
http://52.15.65.240:8080/job/ScaleIO-Juju2-OpenStack-Newton/

**Comment by Andrey-mp** [comment]
But this version is not released now - We've checked only master version.
